print("=== BIODATA MAHASISWA ===")
print("Nama     : Maharaja korga")
print("NIM      : 2611532030")
print("Jurusan  : Informatika")
print("Kelas    : IF-B")
print("Hobi     : Bermain dan mendengarkan musik")
print()
print()
print()
print("       *")
print("      ***")
print("     *****")
print("    *******")
print("   *********")
print("  ***********")
print(" *************")
print("      ||")
print("      ||")
print("      ||")
print("     ||||")